@startuml

title Pavillion Steuerung Klassendiagramm

class Weather {
- weather : Weather
- rain : bool
- windSpeed : int
- humidity : float
- temperature : float
__Setters__
- void setWeather(Weather weather)
- void setRain(bool rain)
- void setWindSpeed(int windSpeed)
- void setHumidity(float humidity)
- void setTemperature(float temperature
__Getters__
- Weather getWeather()
- bool getRain()
- int getWindSpeed()
- float getHunidity()
- float getTemperature()
}

class Motor {
- int time
- stroke : int
- position : int
__Setters__
- setPosition(int pos)
- setStroke(int str)
- setTime(int time)
__Getters__
- int getPosition()
- int getStroke()
- int getTime()
--
- int measureStroke()
- open()
- close()
}

class PavillionControl {
- dateTime : DateTime
__Setters__
void setDateTime(DateTime dateTime)
__Getters__
DateTime getDateTime()
__
- void setup()
- void loop()
- void checkMeasurements()
}

Weather -> PavillionControl : influences
PavillionControl -> Motor : controls

@enduml
